version: '3.7'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud_password
    depends_on:
      - db
    networks:
      - internal
      - web

  db:
    image: mysql:5.7
    container_name: nextcloud_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud_password
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nextcloud_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /path/to/your/certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nextcloud
    networks:
      - web

volumes:
  nextcloud:
  nextcloud_data:
  db_data:

networks:
  internal:
  web:

